### ISSUE TITLE
TensorFlow 2.0

### ISSUE THREAD

**Issue by a-price** [UM-ARM-Lab/mps_shape_completion#3]
Apparently `session` is no longer a thing in TF2 (https://github.com/tensorflow/community/pull/20) so we should update to be able to run the latest version.

**Comment by bsaund** [comment]
In addition to changing the code, the Docker file will need to be changed to pull from `tensorflow/tensorflow:latest`

**Comment by bsaund** [comment]
This pull request addresses this:
https://github.com/UM-ARM-Lab/mps_shape_completion/pull/7

By using tf.compat.v1. This makes tensorflow 2.0 still behave like tensorflow 1.0. 
I'll leave this issue open though, since we may want to do a proper migration. This would break compatibility with older versions of tensorflow though.

**Comment by bsaund** [comment]
This was addressed by https://github.com/UM-ARM-Lab/mps_shape_completion/pull/7 which has been merged
